### ISSUE TITLE
download 42 images only

### ISSUE THREAD

**Issue by koloved** [hopto-dot/Gelbooru-Downloader#2]
i tried to use url and tag, pages:1-7 , and its not work, there is should be around 300 images with the wifu

**Comment by Opagira** [comment]
Автор е#лан. Как я понял нужно заменить в коде :
string url = !searchString.StartsWith("https://gelbooru.com/") ? $"https://gelbooru.com/index.php?page=post&s=list&tags={searchString}&pid={pageID}" : searchString;
на:
string url =  $"https://gelbooru.com/index.php?page=post&s=list&tags={searchString}&pid={pageID}";

**Comment by hopto-dot** [comment]
My code works as intended.

The only reason it won't download the exact amount you expect is because images with less than 18 tags won't be downloaded. Also, animated images won't be downloaded.

![image](https://github.com/hopto-dot/Gelbooru-Downloader/assets/66906618/149c5806-ca22-4035-966a-b164b94cf627)
